### ISSUE TITLE
Definir possíveis ferramentas para o desenvolvimento da documentação 

### ISSUE THREAD

**Issue by IanoMaciel** [IanoMaciel/software-maintenance-and-integration#2]
# Período

**Duração:** 27 a 31/03

# Reunião

**Data:** 27/03 <br/>
**Hora:** 16h às 16h30 <br/>
**Local:** UFAM/ICET <br/>

# Objetivo

- Escolher ferramentas para documentar o plano de desenvolvimento de software
- Criar contas em ferramentas
- Pensar em próximas sprints

# Papeis

|     Membros    |         Função        |
|----------------|:---------------------:|
| Iano Maciel    | Gerente de Manutenção |
| Henrique Simas | ProductOwner          |

# Backlog
| Issue | Descrição | Responsáveis | Status |
|-------|-----------|--------------|--------|
| [#1](https://github.com/IanoMaciel/software-maintenance-and-integration/issues/1) | Definição do projeto e planejamento de sprints |  Iano de Henrique | Em andamento|

# Pareamento

[Iano Maciel](https://github.com/IanoMaciel) e [Henrique Simas](https://github.com/Henr1que-Simas)

**Comment by HenriqueSimas** [comment]
docs(#2): Que tal utilizarmos o próprio GitHub para a documentar o plano de manutenção de software?

**Comment by IanoMaciel** [comment]
docs(#2): perfeito, @Henr1que-Simas. Podemos utilizar também a própria wiki do github para ficar mais profissional.
